Forme/apps/landing_page/urls.py
from django.conf.urls import url
from Forme.apps.landing_page import views
urlpatterns = [
    url(r'^$', views.landing_page, name='landing'),
]

Forme/apps/student/urls.py
from django.conf.urls import url
from Forme.apps.student import views
urlpatterns = [
    url(r'^list/$', views.StudentListView.as_view(), name='list_students'),
    url(r'^create_student/$', views.CreateStudent.as_view(), name='create_student'),
    url(r'^edit_student/(?P<pk>([0-9]+))/$', views.UpdateStudent.as_view(), name='edit_student'),
]

Forme/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'', include('Forme.apps.landing_page.urls', app_name='landing_page', namespace='landing_page')),
    url(r'^student/', include('Forme.apps.student.urls', app_name='student', namespace='student')),
    url(r'^admin/', admin.site.urls),
]

Forme/apps/student/models.py
from django.contrib.auth.models import models


class Student(models.Model):
    first_name = models.CharField(max_length=50, blank=False, null=False)
    last_name = models.CharField(max_length=50, blank=False, null=False)
    age = models.IntegerField(blank=False, null=False)
    about = models.TextField(max_length=250, blank=True, null=True)

Forme/apps/student/forms.py
from django import forms

from Forme.apps.student.models import Student


class CreateStudentForm(forms.ModelForm):
    class Meta(object):
        model = Student
        fields = ('first_name', 'last_name', 'age', 'about')

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age and age > 100:
            raise forms.ValidationError("Too old student")
        return age

    def clean(self):
        cleaned_data = super(CreateStudentForm, self).clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if first_name and last_name and first_name == last_name:
            raise forms.ValidationError("First and last names cannot be the same!")
        return cleaned_data

Forme/apps/landing_page/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect


def landing_page(request):
    return HttpResponseRedirect(reverse('student:list_students'))

Forme/apps/student/views.py
from django.core.urlresolvers import  reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView

from Forme.apps.student.models import Student
from Forme.apps.student.forms import CreateStudentForm


class StudentListView(ListView):
    model = Student
    template_name = 'students.html'

    def get_context_data(self, **kwargs):
        context_data = super(StudentListView, self).get_context_data(**kwargs)
        context_data['page_title'] = 'Student List Page'
        return context_data


class CreateStudent(CreateView):
    model = Student
    template_name = 'create_student.html'
    form_class = CreateStudentForm
    success_url = reverse_lazy('student:list_students')

    def get_context_data(self, **kwargs):
        context_data = super(CreateStudent, self).get_context_data()
        context_data['page_title'] = 'Create Student'
        return context_data


class UpdateStudent(UpdateView):
    model = Student
    template_name = 'create_student.html'
    form_class = CreateStudentForm
    success_url = reverse_lazy('student:list_students')

    def get_context_data(self, **kwargs):
        context_data = super(UpdateStudent, self).get_context_data()
        context_data['page_title'] = 'Edit Student'
        return context_data

Forme/apps/student/templates/create_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Student</title>

</head>
<body>
    <h2>{{ page_title }}</h2>
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    <a href="{% url 'student:list_students' %}">Cancel</a>

</form>

</body>
</html>

Forme/apps/student/templates/students.html
<!DOCTYPE html>
<html>
<head>
    <style>
        table {
            width: 100%;
        }

        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }

        th, td {
            padding: 5px;
            text-align: left;
        }

        table#t01 tr:nth-child(even) {
            background-color: #eee;
        }

        table#t01 tr:nth-child(odd) {
            background-color: #fff;
        }

        table#t01 th {
            background-color: black;
            color: white;
        }
    </style>
</head>
<body>
<h2>{{ page_title }}</h2>
<table id="t01">
    <thead>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>About</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for student in object_list %}
        <tr>
            <td>{{ student.first_name}}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.age }}</td>
            <td>{{ student.about }}</td>
            <td><a href="{% url 'student:edit_student' pk=student.id %}">Edit</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<br>
<a href="{% url 'student:create_student' %}">Create Student</a>

</body>
</html>